apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: staircase-step-3
  namespace: react-money
spec:
  mode: one
  selector:
    namespaces: [react-money]
    pods:
      react-money: ["backend-8fd64c8cc-rcm8x"]
  stressors:
    memory:
      workers: 1
      size: "120MiB"
  duration: "40s"
